version: "3.1"

volumes:
    modules:
    db:

services:
    react:
        container_name: datahub-react
        build:
            context: .
            dockerfile: ./frontend/react.dockerfile
        restart: unless-stopped
        volumes:
            - ./frontend:/app
            - modules:/app/node_modules
        ports:
            - "3000:80"
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: bash -c "npm install & npm run dev"

    php:
        container_name: datahub-php
        build:
            context: .
            dockerfile: ./backend/php.dockerfile
        restart: unless-stopped
        volumes:
            - ./backend/src:/var/www/html
        ports:
            - "3001:80"
        depends_on:
            - mariadb

    phpmyadmin:
        container_name: datahub-phpmyadmin
        image: phpmyadmin:latest
        restart: unless-stopped
        ports:
            - 3002:80
        depends_on:
            - mariadb
        environment:
            - PMA_HOST=mariadb
            - PMA_PORT=3003

    mariadb:
        container_name: datahub-mariadb
        image: mariadb:latest
        restart: unless-stopped
        volumes:
            - db:/var/lib/mysql
            # - ./db:/docker-entrypoint-initdb.d
        ports:
            - "3003:3003"
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_TCP_PORT=3003
            - MYSQL_UNIX_PORT=3003